// <auto-generated />
using System;
using CarSpeed.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarSpeed.Data.Migrations
{
    [DbContext(typeof(CarSpeedDbContext))]
    partial class CarSpeedDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("CarSpeed.Core.Models.CarSpeedEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CarRegistrationNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Speed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimeOfRecord")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CarSpeeds");
                });
#pragma warning restore 612, 618
        }
    }
}
